/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_terasology_TeraOVR */

#ifndef _Included_org_terasology_TeraOVR
#define _Included_org_terasology_TeraOVR
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_terasology_TeraOVR
 * Method:    initSDK
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_terasology_TeraOVR_initSDK
  (JNIEnv *, jclass);

/*
 * Class:     org_terasology_TeraOVR
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_terasology_TeraOVR_clear
  (JNIEnv *, jclass);

/*
 * Class:     org_terasology_TeraOVR
 * Method:    getDisplayDeviceName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_terasology_TeraOVR_getDisplayDeviceName
  (JNIEnv *, jclass);

/*
 * Class:     org_terasology_TeraOVR
 * Method:    getProductName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_terasology_TeraOVR_getProductName
  (JNIEnv *, jclass);

/*
 * Class:     org_terasology_TeraOVR
 * Method:    getManufacturer
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_terasology_TeraOVR_getManufacturer
  (JNIEnv *, jclass);

/*
 * Class:     org_terasology_TeraOVR
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_terasology_TeraOVR_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     org_terasology_TeraOVR
 * Method:    getHResolution
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_terasology_TeraOVR_getHResolution
  (JNIEnv *, jclass);

/*
 * Class:     org_terasology_TeraOVR
 * Method:    getVResolution
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_terasology_TeraOVR_getVResolution
  (JNIEnv *, jclass);

/*
 * Class:     org_terasology_TeraOVR
 * Method:    getVScreenSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_terasology_TeraOVR_getVScreenSize
  (JNIEnv *, jclass);

/*
 * Class:     org_terasology_TeraOVR
 * Method:    getVScreenCenter
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_terasology_TeraOVR_getVScreenCenter
  (JNIEnv *, jclass);

/*
 * Class:     org_terasology_TeraOVR
 * Method:    getEyeToScreenDistance
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_terasology_TeraOVR_getEyeToScreenDistance
  (JNIEnv *, jclass);

/*
 * Class:     org_terasology_TeraOVR
 * Method:    getLensSeparationDistance
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_terasology_TeraOVR_getLensSeparationDistance
  (JNIEnv *, jclass);

/*
 * Class:     org_terasology_TeraOVR
 * Method:    getInterpupillaryDistance
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_terasology_TeraOVR_getInterpupillaryDistance
  (JNIEnv *, jclass);

/*
 * Class:     org_terasology_TeraOVR
 * Method:    getDistortitionK0
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_terasology_TeraOVR_getDistortitionK0
  (JNIEnv *, jclass);

/*
 * Class:     org_terasology_TeraOVR
 * Method:    getDistortitionK1
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_terasology_TeraOVR_getDistortitionK1
  (JNIEnv *, jclass);

/*
 * Class:     org_terasology_TeraOVR
 * Method:    getDistortitionK2
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_terasology_TeraOVR_getDistortitionK2
  (JNIEnv *, jclass);

/*
 * Class:     org_terasology_TeraOVR
 * Method:    getDistortitionK3
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_terasology_TeraOVR_getDistortitionK3
  (JNIEnv *, jclass);

/*
 * Class:     org_terasology_TeraOVR
 * Method:    getYaw
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_terasology_TeraOVR_getYaw
  (JNIEnv *, jclass);

/*
 * Class:     org_terasology_TeraOVR
 * Method:    getPitch
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_terasology_TeraOVR_getPitch
  (JNIEnv *, jclass);

/*
 * Class:     org_terasology_TeraOVR
 * Method:    getRoll
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_terasology_TeraOVR_getRoll
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
