/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_terasology_TeraOVR */

#ifndef _Included_org_terasology_TeraOVR
#define _Included_org_terasology_TeraOVR
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_terasology_TeraOVR
 * Method:    initSDK
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_terasology_TeraOVR_initSDK
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
